ankit071105/Ticket-Booking

Dockerfile
Working on Cli
Project run on localhost 8080 , on gcloud
to run that Dockerfile
build command
`docker build -t my-html-app .`
run command
`docker run -d -p 8080:80 my-html-app`
=> Feature(Docker) : add production-ready Dockerfile for frontend client #122

buy.html, index.html, sell.html, train_buy.html, train_sell.html
changes social icon (twitter)
Several GitHub repositories have recently implemented changes to update the Twitter icon to the new "X" logo in line with Twitter's rebranding.
These updates reflect efforts to stay current with the evolving branding of Twitter.
Fixes #290 
Before:
After:
=> update social media icon

buy.html, sell.html, train_buy.html, train_sell.html
Add dark mode toggle in the four pages of your website which makes the website look consistent as the user scroll or navigate.
Fixes #421 
Before:
After:
video:
https://github.com/user-attachments/assets/c0bb2aca-2e15-4979-8bdc-e1e6eaa513d6
=> Add dark theme toggle

contributor/contributor.css, contributor/contributor.html
#442 
Fixes #442 
Improve the UI of the  font on contributor  page
before:
after:
-Improve feature and UI.
=> improve front font on contributor page.

client/login.html
#487 login page UI Enhanced
I adjusted width in login page
Fixes #487 
login page
=> login page ui enhanced

client/forgot_password.html, client/register.html
#488 Register and forget password page scrolling issue fixed
I adjusted heights and width to remove scrolling effect
Fixes #488 
=> Register and forget password page scrolling issue fixed

contributor/contributor.css, contributor/contributor.html
Currently the profile cards are looks very simple.
I've added some design and also added hover effect on cards which enhanced them.
Fixes #499 
Issue: Add hover-effect on cards of our contributors page. #499
Before:
After:
https://github.com/user-attachments/assets/16cf3805-4789-438d-88dc-421be8d2a269
I've done the self-review of my code. It gives the correct output.
=> Enhanced the profile cards on contributor page

pnr_check.html
Added a PNR checker
Fixes #(issue)
Added page
Added code
- [✔️ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
=> Added PNR Checker 

main.css
When on Sell and About page, the mouse cursor can't be seen over the window.
Probably because the cursor was set to none.
https://github.com/user-attachments/assets/e53d5a27-8ce0-4aa8-ad40-98c5adeaa173
https://github.com/user-attachments/assets/1dc61476-d684-46db-8f3f-83907fb87ed0
=> #567-mouse-hide-fix

buy.html
Fixes #579 
- **Issue**: Users were able to enter more than four digits for the year in the "Date of Journey" field, resulting in an invalid date format On this page - https://ticket-booking-blue.vercel.app/buy.html.
- **Fix**: Implemented restrictions to ensure the year part of the date input does not exceed four digits.
1. **JavaScript Validation**:
- Added a validation script to enforce strict date input. The script checks that the date entered follows the `YYYY-MM-DD` format and restricts any input beyond 10 characters, preventing users from entering more than four digits for the year.
```javascript
document.getElementById('journeyDate').addEventListener('input', function() {
const datePattern = /^\d{4}-\d{2}-\d{2}$/;
if (!datePattern.test(this.value)) {
this.value = …
```
=> Fixes #579: Resolved entering date issue

chatbot.js
#584 chatbot-fix
The previous hardcoded chatbot has been refactored to a dynamic chatbot that leverages the Llama 3 model. All requests are now forwarded to the API, allowing for more flexible and accurate responses.
- Replaced the hardcoded logic with API calls to the Llama 3 model.
- Implemented dynamic request handling to improve response delivery.
- Enhanced overall performance and user interaction.
This update significantly enhances the chatbot's functionality, providing users with a more responsive and intelligent conversational experience.
https://github.com/user-attachments/assets/ad0a2a3d-d439-453a-ba8b-5b005e21df02
=> #567-chatbot-fixed

ModernSlaveryAct.html, privacy.html, terms.html
now the user interfarece of the section terms of use, privacy policy and modern slavery is enhanced.
additionally i add header section to the terms of use.
my issue no. is #613
=> ui of terms of use,privacy policy and modern slavery enhanced

buy.html, index.html, train_buy.html, train_sell.html
This PR resolves an issue with the logo navigation on the Buy and Sell page. Previously, clicking the logo did not redirect users back to the home page. Now, with the addition of an anchor tag on the logo, users can easily return to the home page from any page within the application. This change ensures a more intuitive and consistent user experience across all pages.
Fixes #611
- **Bug fix** (non-breaking change that corrects the logo’s missing anchor tag)
- **Chore** (enhances navigation functionality for a better user experience)
=> Fixes 611#: Resolved the logo anchor

contributor.css
In contributors page , in Dark mode, text was not visible earlier. now its visible
Fixes #564 
Before:
After:
=> contributors dark mode update

sell.html
This PR improves the Sell Ticket page of the ticket booking website by:
- Removing multiple logos from the footer.
- Aligning and resizing the cards.
- Adding hover effects to the cards for better user interaction.
**Fixes**: Issues #626, #489, #637.
-  Bug fix
=> Improved Sell Ticket Page Layout and Optimize Footer

contributor.js
Fixes #553 
I fixed the problem of fetching page wise data through Github API . Previously only a part of data was being fetched . 
I have upgraded it fetch entire data. 
Also, I have Fixed Total contributions which was showing 0 earlier. 
=> Fixes #553 : Fixed the contributors and Total Contributions data

faq.css
(already much solved)
- added proper css features like margin-top  & margin-bottom
- ensures no further  overlapping with any section
Fixes #769 
- Then
- Now
@ankit071105
=> [BUG] `Home Page` Elements are no more Concinding over other 

index.html
Fix #832 
- Sets the initial visibility of the scrollTop button to hidden, improving the overall user interface by reducing clutter.
- The button becomes visible only after scrolling down more than 100 pixels, enhancing usability and encouraging seamless navigation back to the top.
@ankit071105
Pls assign me, give me labels like gssoc-extd, hacktoberfest-accepted, and level.
=> Enhanced ScrollTop Button Functionality

about.html, buy.html, contactus.html, contributor.html, index.css, index.html
Added functionality to highlight the active link in the navbar, providing a clearer navigation experience for users.
The active link is now visually distinct, helping users identify their current location on the site with ease.
This enhancement improves usability, especially for multi-page navigation, ensuring users can easily track their browsing path.
Fixes #815 
https://github.com/user-attachments/assets/fbfd3a46-39f8-4f15-a6bd-96f78998b67d
=> Add active link highlight in navbar for improved navigation

about.html, buy.html, contactus.html, contributor.html, index.html, styles.css
@ankit071105 
I have removed the extra gap from the icon and the name of the website, and added home link to it for navigation and changes it for all the pages
Kindly check it out
https://github.com/user-attachments/assets/1b8f3553-c585-4cf9-94de-396941ea5b90
Fixes #(issue)
=> fixed gap, added home link, added same navbar for all pages

buy.html
In dark mode, text was not visible clearly for book ticket, which is now visible
Fixes #772 
Before:
After:
=> buy ticket page dark mode update

contactus.html
Fixes #879
1. Added validation to allow only trusted email domains: `gmail.com`, `outlook.com`, `yahoo.com`, `protonmail.com`, `icloud.com`, `tutanota.com`, and more.  
2. Displays an alert message if the email is from an untrusted domain and blocks submission.  
3. Ensures data integrity by filtering spam and temporary emails. 
@ankit071105
Pls add level, gssoc-extd, hacktoberfest-accepted.
=> Added Trusted email validation functionality in contact us form

header.html
=> organised the header

book_condition.html, forgot_password.html
1. Improved Styling and Color Scheme
Background Color: A lighter background color #f2f7fc was applied to create a pleasant contrast against the text, improving readability.
Header and Section Titles: Made text color darker (#333 for the header, #00509e for the section titles) for better contrast.
Box Styling: Each .box section has a subtle left border and background color for a visually appealing, card-like effect, enhancing readability and separation of content. The hover effect on the boxes adds interactivity.
2. Footer Enhancements
Footer Layout: Adjusted footer sections to be more organized, using flex for a balanced, centered look on large screens.
Footer Colors: Set a background color of #1e2a38 with text color #b5fdf4, maintaining readability against the darker background and …
=> Enchancing the Book_condition.html

styles.css
Fix #903 
This PR implements a solution to hide the `circle` on screens 768 pixels wide or smaller. The visibility is controlled using CSS media queries to enhance the mobile user experience.
@ankit071105 
Pls give me labels like gssoc-extd, level and assign me this issue.
=> Hiding Cursor on Mobile View

contributor.css
changes the heading color to white when switched to dark mode  in contributors section.
Fixes #914
SCREENSHOTS 👍: 
=> change the heading color to white when switched to dark mode 

contributor.css, index.css
Changes the color of the heading tag in dark mode of home page
Fixes #915
=> Changes the color of the heading tag in dark mode of home page

client/login.html
This PR adds a "Remember Password" feature on the login page, enabling users to save their password for future logins. This feature helps streamline the login process by storing credentials based on the device/browser settings when enabled.
Fixes #907 
Checkbox Addition: A "Remember Password" checkbox has been added to the login screen.
Automatic Login Setup: When selected, the application will remember the user's login details for future sessions (subject to device/browser permissions).
- This change requires a …
=> "Remember Password" Option

contactus.html
On the Contact Us page name and email field validation were added. now name field only accepts alphabets,and the email only accepts a valid email address/
Fixes #999 
https://github.com/user-attachments/assets/13a584ee-7b56-44f0-9188-87ecd8c1b9e9
=> 🛠️FIX : Contact us page name and email field validation added

main.css
FIXED the OVER-SIZE of Social SIDE-BAR
BEFORE : 
AFTER : 
Fixes #(issue)
=> FIXED the OVER-SIZING of Social SIDE-BAR

sell.html
Updates the calendar date validation to prevent users from selecting dates prior to the current date, ensuring valid and up-to-date submissions.
Fixes #1014 
=> 🛠️FIX : Calendar Date Validation to Restrict Past Dates

book_condition.html
Fixed` Booking Condition` page style .
Fixes #1020 
https://github.com/user-attachments/assets/707e4e93-489b-42ff-a6bb-2dcdc4559602
=> 🛠️FIX : Booking Condition page style

contactus.html
Removed the duplicate footer section that was present on the page, consolidating the footer content into a single instance. This cleanup reduces code duplication and technical debt.
Closes #1016
- Identified and removed the redundant footer section
- Verified that the remaining footer section is fully functional and visually consistent
- Ensured there are no regressions or missing content
1. Load the page and scroll to the bottom
2. Verify there is only a single footer section present
3. Interact with the footer (links, copyright, etc.) to ensure functionality is intact
- No external libraries or dependencies were added
- Followed existing HTML/CSS structure and patterns
=> fix: Remove Duplicate Footer Section for Cleaner Codebase

index.html
Inside navbar of index.html it is overlap with the login button  so i fixed this code pleased check out
previously it is showing
Fixes #(issue)
https://github.com/user-attachments/assets/f39915df-9e77-4ce9-939c-f90ff25f1ce2
=> Profile icon fixed index.html page

index.html, profileedit.html, testp.html, testp.js
Hello, PR
Add Edit Profile Feature in Profile Page done - #994
https://github.com/user-attachments/assets/ed24ae2d-6994-4178-8400-b91989653091
=> Add Edit Profile Feature in Profile Page done ! #994

register.html
Fixed the BUG of Register Page
BEFORE : 
AFTER : 
Fixes #(issue)
=> Fixed the BUG of Register Page

index.html
Fixed the Double Profiles Problem in Menubar
BEFORE :
AFTER : 
Fixes #(issue)
=> Fixed the Double Profiles Problem in Menubar

main.css
Fixes #1096 
-  Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
=> static icons animation added and appropriate color on hovering added
