ankit071105/Ticket-Booking

- index.html
This pull request fixes the issue where the dark/light mode toggle button showed the same icon for both modes. Now, the icon dynamically changes:
- **Sun icon** in dark mode.
- **Moon icon** in light mode.
- Added logic to switch the icon based on the active theme.
- Instant icon update when toggling between modes.
- Tested across multiple browsers and devices to ensure proper functionality.
https://github.com/user-attachments/assets/39576338-5695-473a-b7a7-ee57788dddf2
The video demonstrates the icon changing correctly when toggling between dark and light modes.
> fix the Dark/Light Mode Toggle Button Icon

- index.html
I improved the navbar and the added logo 
please it make label under the gssoc or  the hacktoberfest  and add level
> logo is added

- server/.gitignore
- server/README.md
- server/app.js
- server/config/db.js
- server/controllers/v1/auth_controller.js
- server/middleware/protectRoute.js
- server/models/user.js
- server/package-lock.json
- server/package.json
- server/routes/auth.js
- server/server.js
Done the Backend Part of Authentication 
created the restful APIs for the Register And Login 
JWT added , hashing done, will add other features later.
Just Deploy the API on Server then we are ready to Work on Frontend Part.
> Signup/ Login Backend Part Done

- index_changed.html
Altered the Navbar contents , from navbar container
> Changing the navbar

- app.js
Overview: This pull request introduces significant improvements to the app.js file, focusing on code maintainability, readability, and user experience for the bus and train ticket submission functionalities.
Key Changes:
Code Duplication Reduction: Implemented a common function to handle both bus and train ticket submissions, adhering to the DRY (Don't Repeat Yourself) principle.
Form Validation: Added validation checks to ensure that all required fields are filled out before submission, enhancing user experience by preventing incomplete submissions.
Constants for Pricing Logic: Introduced constants for seller deduction and buyer fee calculations to eliminate magic numbers, making the code more understandable and easier to modify.
Improved Readability: Utilized template literals for …
> Refactor app.js for Enhanced Maintainability and User Experience

- buy.html
This pull request updates the buy.html file to enhance the structure and user experience of the Buy Tickets page. The following changes have been made:
Improved HTML Structure:
Organized the layout of the ticket selection and display sections to improve readability.
Ensured semantic HTML tags are used for better accessibility and SEO.
Responsive Design Enhancements:
Added responsive design elements to ensure the page is user-friendly on various devices.
Adjusted the CSS styles to provide a more visually appealing layout.
Dynamic Content Display:
Included sections to dynamically display available tickets based on the user’s selection (bus or train).
Implemented clear labels and headings for better user navigation.
Footer Addition:
Added a footer section for branding and copyright …
> Updated HTML Structure for Buy Tickets Page

- train_buy.html
This pull request introduces several improvements to the train_buy.html file to enhance user experience, accessibility, and maintainability. The key changes include:
Semantic HTML: Wrapped the main content in a <main> tag for better semantic structure.
Accessibility Improvements: Added aria-label attributes to the "Buy Ticket" buttons to improve screen reader compatibility.
Dynamic Ticket Listing: Suggested implementing JavaScript to dynamically generate ticket cards, making it easier to manage ticket data.
Responsive Design Enhancements: Ensured that the layout adapts well to various screen sizes, improving mobile responsiveness.
User Feedback Implementation: Proposed adding a confirmation message or modal after a ticket purchase to inform users of successful transactions.
Error …
> Enhance train_buy.html for Improved Usability and Accessibility

- bus_sell.html
This pull request introduces several improvements to the bus_sell.html file to enhance its accessibility, usability, and maintainability. The following changes have been made:
Semantic HTML: Wrapped the main content in a <main> tag to improve semantic structure.
Accessibility Improvements: Added aria-required attributes to input fields for better screen reader support.
Input Type Changes: Changed the phone number input to type="tel" to provide a mobile-friendly keyboard.
Validation Patterns: Added pattern attributes for the phone number input to enforce a 10-digit format.
Placeholder Text: Included placeholder text in relevant input fields to guide users on expected formats.
Error Handling: Introduced a section for displaying error messages, enhancing user feedback during form submission. …
> Enhance Accessibility and Usability of bus_sell.html

- README.md
Thanks @ankit071105 for assigning me this Issue.
- Fixed #18 
Please merge this PR.
> Added All Contributors' Profile Pictures and Fixed Readme.md

- index.html
the site has better responsiveness now for all sizes of screens
> Updated responsiveness

- app.js
- bus_sell.html
- buy.html
- train_sell.html
Changed the input fields in the train-ticket section and added some key input options.
> Changed Input Fields

- buy.html
- buy_bus_ticket.html
- buy_train_ticket.html
Description of the Solution:
This solution separates the Bus Ticket and Train Ticket options into individual pages. The changes include:
Creation of a new bus_ticket.html page to display bus ticket options.
Creation of a new train_ticket.html page to display train ticket options.
Updated navigation to include links to these separate pages for better user experience and organization.
To this
Ad I make changes in index page for the image to fit the page as per window size
> "Separation of Bus Ticket and Train Ticket Pages for Improved User Navigation"

- client/login.html
- client/register.html
- server/README.md
- server/server.js
Add Frontend for Login and Signup and Integrated that with the backend API
> Saurabhvybs

- index_changed2.html
> Altered The footer

- index.html
I have added the follow us on social sidebar
> added social-icons sidebar

- index.css
- styles.css
Whole images were not properly shown ,so it was corrected
> Image Out of Bounds Was corrected

- bus_sell.html
- buy.html
- buy_bus_ticket.html
- buy_train_ticket.html
- faq.css
- index.html
- sell.html
- styles.css
- train_buy.html
- train_sell.html
fix issue: #51 
Hi, I have successfully resolved the issues of adding the 'move to top' button, linking the NavBrand logo, and connecting the FAQ section. Please review the changes, and let me know if any further adjustments are needed. Thank you!
> Fix issue: #51 add bottom to up button and nav logo redirect and  add FAQ section

- index.css
- index.html
Added move to top button to website 
Added faq section
Fixed issue of nav logo link not working now nav logo redirects to home
> added move to top button and faq section 

- index.html
- Updated the hover effect for the social media icons to enhance user interaction.
- Adjusted spacing between icons to prevent overlapping on hover.
- Fixes #123
> Improve socials sidebar icons hover effect

- about.css
- faq.css
- index.html
https://github.com/user-attachments/assets/89a6b278-dd8e-4c8c-8e3c-a13b82c89f27
#143 
Implemented that slow move of the hidden text when pressed in the FAQ Section, using CSS and JS. 
Also, encountered text-formatting problems, and fixed empty lines. The FAQ Headings used to turn 90deg in a certain media query, commented it out. The colour turned a certain white, and changed it to original black.
> Solved the #143 idea.

- index.css
- index.html
- package-lock.json
1. Refined the button's gradient and color scheme to match the project’s theme.
2.  Fixed the CSS transition issue by ensuring all properties are properly applied and animated on hover.
3. Ensured responsive and smooth hover effect transitions, along with active and focus states.
4.  Updated box-shadow and padding adjustments for better visual appeal and user interaction.
> Improve Button Styling and Fix Transitions for Responsive UI

- client/login.html
- client/register.html
- package-lock.json
Reference issue #138 
issue solved
User can show their password entered
Add gssoc-ext  lable
> password show button added in login/register page

- index.html
fix map size and add contact section
> reduce map size 

- client/forgot_password.html
- client/login.html
- client/register.html
#140
https://github.com/user-attachments/assets/1e876b4b-8ccd-4740-8553-a9892363cd08
i  have all the changes
> Adding forgot password option

- styles_N1.css
> Changed The Main Body(Ticket MArketplace)

- buy.html
- footer.css
- index.css
- index.html
- sell.html
- styles.css
- styles_N1.css
- train_buy.html
- train_sell.html
https://github.com/user-attachments/assets/13a402a7-5827-4a1a-9ba6-71ef9714b62a
**Update**
-Footer is added in every subpage
-All the icons and the services are clickable links
-It matches the theme of the "Ticket Booking"
@ankit071105  Please look into it
> Developed the footer section [Fixes #181]

- README.md
This is with reference to #198 . I have made the changes as proposed in my issue. Please let me know if any changes are required.
> Documentation Update 

- aboutNew.css
- indexNewChanged.html
> Changed The UI 

- about.css
- index.html
- main.js
hay @ankit071105 , I add one more section which is testimonial its helps to show your client experience 
so please check it and add label gssoc-ext and level according to work
> create responsive testimonial section

- faq.css
- index.html
I added hover in the FAQ header as well as in down arrow so that it matches with the website.
Issue No. #178 
Before:
https://github.com/user-attachments/assets/60f0af16-a153-459f-92a6-50c931e1a763
After:
https://github.com/user-attachments/assets/60d6ff11-c6dd-42a7-8527-0847e58d9a60
Thank youuu...
> Added hover effects in the FAQ sections

- about.css
Fix #159 and make card section responsive
> make card section responsive

- about.css
- index.html
please add gssoc-ext and hacktoberfest-accepted labels @ankit071105
> Fixes #192: home page cards for mobile view

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/greetings.yml
This Pull Request adds standardized templates for both Issues and Pull Requests to ensure consistent formatting and information when reporting bugs or submitting code changes.
- Added a .github/ISSUE_TEMPLATE/issue_template.md for bug report submissions.
- Added a .github/PULL_REQUEST_TEMPLATE.md for pull request submissions.
- Improves the clarity and consistency of Issue and PR submissions.
- Helps maintainers and contributors understand the context and details of submissions.
> Feature ISSUE/PULL REQUEST Template

- README.md
Add the Contributers Photo and add text in `Our Valuable Contributors` section
Fixes #224 
> Add Contributors Photo

- index.css
- index.html
Fixed the navbar list for mobile view.
Fixes #310 
> fixed navbar bug

- index.html
This pull request enhances the Contact Us section by adding the following features:
1. Hover effects for h2 and h4 elements:
- Text color changes to white.
- A glowing effect in the theme's greenish-blue color (#00bfa6).
2. Slight size increase on hover.
3. Smooth transition animations to improve user experience.
These updates align the design with the existing color scheme and improve the visual interactivity of the website.
Kindly merge it. 
fixes: #152
> Enhance Contact Section: Added Hover Effects with Glow and Size Increase

- about.css
- about.html
Pull Request for issue: Updating the About Us page #303 
In this PR I have beautified the About Us page by adding color, image, shadow, and hover effect. By doing this the page has become more attractive to the user. I have used one of the images in the directory to give a column layout to the page.
##Fixes 
Before Changes:
After Changes:
> Updating the About Us page #303

- Ticket-Booking-main1/client/package-lock.json
- Ticket-Booking-main1/index.html
- Ticket-Booking-main1/server/.gitignore
- server/app.js
- server/config/db.js
- server/controllers/v1/auth_controller.js
- server/package-lock.json
- server/package.json
- server/routes/auth.js
added email functionality in backend and contact form in frontend
frontend:
output:
please add level3 and gssoc-ext before merge
> added email functionality

- index.html
Added a cursor trail
sample
- [ ✔️] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> Added A cursor trail

- client/login.html
Hello, PR
Fixed issue number - #291
Issue fixed -
> Fixed icon box border & shadow in Login page ! #291

- client/login.html
- client/register.html
- server/Dockerfile
> Dockerfile

- client/login.html
- client/register.html
> added validation to forms

- contributors.html
- index.html
- pqr.css
- script1.js
This feature will help recognize contributors, encourage community involvement, and showcase the work done by everyone. It will also make it easy for users to see who contributed and follow the project's progress.
Fixes #(issue)
Added contribution Page
https://github.com/user-attachments/assets/5494a947-c971-451e-bf6c-d3c90876cda0
Plz review @ankit071105 
> Fix issue #338 Add contribution Page

- footer.css
- index.css
The visibility issue is fixed by adding proper margin to the footer.
Fixes #323 
How it looked before:
> fix: alignment issues

- index.html
Created a feedback form at the bottom for better customer engagement
Fixes #388 
> Added feature in index.html

- index.html
Fixed the image card
Fixes #(issue)
- [✔️ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> Fixed the image card

- index.html
Updates the "Name" field in the _**Feedback form**_ section to only accept alphabetical letters (a-z, A-Z), preventing invalid or spam submissions.
Fixes #410 
Before 
After
> 🛠️ Fix : Feedback form - "Name" Field Validation

- index.html
- main.js
fixed the feedback-cards and added proper answers
Fixes #(issue)
- [✔️ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> Fixing the Feedbackcards

- index.html
Fixes #(issue)
https://github.com/user-attachments/assets/fde1e7fe-a07b-47e4-a4e4-8f03b0007ece
> Contact button on navbar is redirecting to contact section.

- about.html
- index.css
- index.html
I've added a new page the about us section to the website as it was not responsive before.
Fixes #417 
Bug fix 
https://github.com/user-attachments/assets/91dc3a67-a65e-4605-a822-f65fb47e99f6
https://github.com/user-attachments/assets/b5ef7ed1-44c1-48aa-8f51-69087a85d373
>  resolved the bug of the about us section

- about.html
- buy.html
- contributors.html
- index.html
- profile.html
- sell.html
- train_buy.html
- train_sell.html
@ankit071105 can you please review this , thank you.
issue #407 solved.
https://github.com/user-attachments/assets/5bedbfe3-41fa-4455-8823-ed97e9b3be84
> multi language support system has been added

- index.html
>>your nav bar toggle  button and login  button collide together to i resolve this issue.
Fixes #390 
>>space issue between login button and  Toggle button.
>>>Before.
>>>After.
- [Y] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> nav bar issue solved.

- profile.html
- profile.js
1.Accessibility Enhancements: Added aria-label attributes for interactive elements like buttons, inputs, and images for screen
readers.
2. Form Improvements:
Added type="email" for email validation.
Added type="tel" and pattern for phone number validation.
Used required for mandatory fields.
3.Responsive Design: Added media queries to ensure a better layout on smaller devices (e.g., stacked form inputs).
4.Button Structure: Replaced div-based buttons for social logins with actual button elements to improve semantics.
5.Download Button Hover: Styled buttons for better visual feedback when hovered.
6. Profile Picture Upload Validation: Only image files are allowed. If a non-image file is selected, an alert is shown.
7. Form Validation:
Simple validation checks for:
Email structure (must …
> Updated profile.html and profile.js

- index.html
**Description**
issue #413 
->Implemented Responsive FAQ Component: Developed a user-friendly FAQ section that adapts seamlessly across various screen sizes, ensuring accessibility for both desktop and mobile users.
->Added Hover Effects: Enhanced the user interface by incorporating hover effects on the FAQ items, improving interactivity and visual feedback, making the FAQ section more engaging.
https://github.com/user-attachments/assets/85262651-8a94-44d4-9a3a-bb7f0b1483a3
->Implemented Responsive FAQ Component: Developed a user-friendly FAQ section that adapts seamlessly across various screen sizes, ensuring accessibility for both desktop and mobile users.
->Added Hover Effects: Enhanced the user interface by incorporating hover effects on the FAQ items, improving interactivity and …
> Improve FAQ Section Design with Hover Effects and Animations

- sell.html
Fixed the repetition of logo Ticket Marketplace on the sell page for desktop view as well as mobile view.
Fixes #387
> Now logo appears only once in the sell page.

- buy.html
- sell.html
- train_buy.html
- train_sell.html
Added chatbot in the four pages of the website like buy/sell, train-buy/sell pages. these changes make the website look consistent throughout the pages scroll by the user. 
Fixes #420 
Before:
After:
video:
https://github.com/user-attachments/assets/6520f93a-6721-4590-9f95-e359c3378006
please @ankit071105 merge this pr and add level 2 or level 3 label to it, as I made changes on four pages.
> Add chatbot 

- server/controllers/v1/ticket_controller.js
- server/middleware/verify_mail.js
- server/models/ticket.js
- server/routes/auth.js
Hey @ankit071105 
I have updated backend for few more functions.
Added routes for buying tickets and viewing histroy .
where we can save tickets purchased by the user.
Also we can fetch the ticket buying history of a particular user in recent order.
It handles all error properly.
These routes can be use in frontend to allow user to buy and save tickets.
And also they can see their ticket anytime they login.
Can be used to add more personalised feature for user.
> Updated backend to save ticket purchased by user

- buy.html
Redesigned the form, changed color, alignment,size
Fixes #408 
Before
After
> Booking Form enhanced

- client/login.html
#396
In this issue I fixed the login page. in the same login page two login designs and I removed one and I adjusted heights and widths of the actual login UI
Fixes #396 login page issue fix
> login page ui fixed

- contributor/contributor.css
- contributor/contributor.html
#443 
Fixes #443
before:
after:
-Improve the UI of the page 
- [x ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> Improve UI of the footer of contributor page

- buy.html
- sell.html
Added a progress bar on the Buy and Sell ticket pages similar to the UI of the home page.
Fixes #428
> Added progress bar similar to home page on Buy and Sell ticket pages.

- index.html
- script.js
- script1.js
- styles.css
This pr has the review section , that is responsive for every screens. User can see the reviews by scrolling left and right. 
Fixes #451 
https://github.com/user-attachments/assets/6cd11c3d-726d-4c4d-a14f-eeb4297a47c3
- [yes, self-reviewed ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> responsive review section added

- index.html
Due to errors in webpage Resolved issue of files
> Added Files Seperately

- main.css
Due the errors added several files css to one files removed from index.html made a css file name main.css
> Seperated Css files that creates an error

- index.css
- index.html
- styles.css
- styles_N1.css
It fixes Text Visibility in Dark mode and also when hovering it
Fixes #435 
> Fixed Text Visibility

- about.html
I have added a home button on the nav bar and removed the additional home button present , to improve the UI of the website
Fixes #425 
> Added home button on NAVBAR , on about us page

- index.html
- privacy.html
This PR makes the Privacy Policy link working.
Fixes #392 
> This PR is related to issue #392.Privacy page link working

- client/login.html
#490 login Auth issue fixed in login page.
added scripts to login.html to fix the issue.
Fixes #490 
Uploading Login Page - Google Chrome 2024-10-21 20-53-23.mp4…
> Login with Google is not working 

- sell.html
- user_reviews/backend/package-lock.json
> Revamp the selling page

- Ticket-Booking-main1/index.css
- index.css
- index.html
aligned the next and previous slide arrow button
Bug fix
> solved #469

- styles.css
- train_sell.html
This PR addresses two UI issues:
1. Removes the duplicate "Ticket Marketplace" title from the navbar to reduce confusion and clutter.
2. Fixes the positioning of the submit button, ensuring it's fully visible and accessible to users.
Resolving these issues is essential for improving user experience, ensuring clear navigation, and maintaining functionality
Fixes #486 
> change sell tickets

- index.css
- index.html
- main.css
Fixes #504 \
-enhancement
>>>Before.
>>>After.
> transform feedback section.

- .github/workflows/pr-checker.yml
Closes #481
This workflow ensures that every pull request description includes an associated issue number for better tracking and clarity. If the required format is not met, contributors will receive clear feedback on how to correct it.
**When the PR description does not meet the required format (missing the issue reference):**
- **PR description:** Fixed bug
- **Output:**
The PR description should include the issue number assigned to you. ⚠️
##[error]An issue reference like 'Fixed #<issue-number>' must be included in the description.
- **PR description**: Fixed # or Issue number # or Closes #
- **Output:**
PR description is valid.
All checks passed.
@ankit071105  please assign all the labels given at issue #481
> created pr-checker

- index.html
The logo of ticket booking did not redirect to the top of the page initially which is solved by this PR.
Fixes #(issue)
https://github.com/user-attachments/assets/aa92140c-835d-410c-95be-d75ec290f0e9
> FIXED : [BUG] Ticket booking icon the footer not functional #485

- index.css
I have fixed the horizontal scrolling issue pls check it
Fixes #508 
> fixed horizontal scrolling

- contributor/contributor.css
- contributor/contributor.html
The footer on our contributors' page is not matched with the other page of the website which makes that page different from the website.
I've solved this issue by adding correct footer on the contributor page.
Fixes #477 
Issue: Add correct footer section on our contributors page #477
Before:
After:
I've done the self-review of my code. It gives the correct output.
> Add correct footer on contributor page

- index.html
solved #470 
now continue with google button in login page is working
> solved #470

- faq.css
- faq.js
- index.css
- index.html
> faq bug Sloved Issue #536 

- buy.html
Modified the ui of the buyticket page
Fixes #418 
Enhancement of the ui
https://github.com/user-attachments/assets/4fc4c6b2-2abf-45dc-a7d5-a4942055dd8f
> Modified the ui of the buyticket page

- index.html
- styles.css
- terms.html
This PR resolves the bug of Terms of Use link not working.
Fixes #495 
> This PR is related to issue #495.Terms of use page created.

- index.html
- main.css
This pull request will close issue #501.
Fixes #501 
1.  Centralized the alignment of slide changing arrows inside circular border.
2.  Added border to slide changing arrow's outer circular and changed background color to black for differentiability (to prevent camouflage with social links menu) and better visibility.
3.  Changed color on hovering the slide changing arrows.
4.  Changed color of arrows in FAQ section for better visibility.
- Bug fixes mentioned in #501.
**Slide changing Arrow**
**Slide changing arrows on hovering--**
**FAQ --**
- [YES] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> Fix Arrow Visibility, Hover Color, and Alignment Issues in Navigation

- ModernSlaveryAct.html
- help.html
- index.html
- travelAware.html
Fixes #506 
This pull request introduces a new Help Center page, a section on the Modern Slavery Act, and a Travel Aware page. These additions have been designed with a modern Styling with responsive design to enhance user experience and accessibility. 
- The **Help Center** provides a centralized resource for users to find answers to common questions and troubleshoot issues. 
- The **Modern Slavery Act section** details the company's commitment to ethical sourcing and human rights. 
- The **Travel Aware page** offers travel tips and advice for users planning trips.
- All the redirecting linked been added in the footer also.
https://github.com/user-attachments/assets/e7085af6-ea5c-4bd8-8491-f4d694966f3b …
> Added Help Center , Modern Slavery Act, and Travel Aware with styling 

- .vscode/settings.json
- index.html
Add Progress Radial Effect . 
close #456 
This will change accordind to take tme to submit.
> Add Submite Progress and fix submit button

- terms.html
This PR includes the following updates for the 'Terms of Use' page:
- Redesigned the layout to improve readability and user experience.
- Made the page fully responsive across different screen sizes.
- Added a sticky table of contents for easy navigation.
Fixes #550 
https://github.com/user-attachments/assets/3a500717-139e-4e30-91d0-73b34c8fc4f3
> Improve "Terms of Use" Page Design 

- index.html
It removes the another two nav_buttons which fixes the UI
Fixes #572 
> "Removed multiple nav_buttons"

- CODE OF CONDUCT.md
As per the issue #571 
I have added
Our Pledge
Our Standards
Enforcement Responsibilities
Scope
Pull Request Guidelines
Enforcement
Enforcement Guidelines
Attribution
Conclusion
Fixes #571 
> Successfully Updated CODE OF CONDUCT.md

- index.css
- main.css
- styles.css
The .slider, slide, .slide img and .nav_buttons has multiple styles defined in multiple css files which was removed in this PR. For better readability and to prevent the styles overriding each other.
Fixes #528 
- Duplicate styles removed
- Code readability increased
> Css files fix

- Contribution.md
I've added a file that consists of a project structure, including a dedicated section for project organization, a detailed pull request process, and clearer guidelines for issue reporting. I hope you find these changes beneficial.
Could you please add the labels "gesso-ext" and "hacktoberfest" and merge the pull request? Thank you!
> Fixes #540

- index.html
- main.css
it fix the feedback box resize problem
Fixes #535 
after fix
before fix
> feedback box fixed

- book_condition.html
- index.html
Fixes #551 
This PR introduces the Booking Conditions page for the online ticket booking web application. The page includes clear, well-defined sections outlining the terms and conditions that users must agree to when booking tickets. Each condition is placed within distinct, visually appealing boxes that separate the information for easy readability and user engagement.
https://github.com/user-attachments/assets/e21503e1-b363-44f2-a92a-ba2f1579ca6a
> Adding "booking condition "page

- quota.html
This page describes the quota system for the different sections of society , for reservation and confirmations
Fixes #(issue)
- [ ✔️] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> Added Quota Page

- index.html
- visi.css
- visi.js
Hello, PR
Add new feature - #542
Add Visitor Counter feature done properly -
> ✨Add Visitor Counter feature done ! #542

- seatAvail.html
Added A Train Seat Availability , describes the all conditions of the seat availability by online and through IRCTC
Fixes #(issue)
- [✔️ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> Added A Train Seat Availability

- ModernSlaveryAct.html
- book_condition.html
- help.html
- privacy.html
- quota.html
- seatAvail.html
- terms.html
- travelAware.html
now footer section is added to terms of use,privacy policy and etc sections 
my issue no. is #555
> add footer to some sections

- buy.html
I adjusted the form layout and design for a good looking , i considered the theme of the sit and rearranged the whole code also took care of the easy understanding of the page code and removed unwanted code lines to make the run faster
Fixes #(issue)
form layout
- [ yes] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> buy form UI updated

- index.html
Changed the way the feedback form used to look
Fixes #(issue)
Revamped and formatted the feedback form.
Before:
After:
> revamped the feedback form

- .vscode/settings.json
- about.html
- help.html
- index.css
- index.html
Fixes #(issue)
okayy so those two committ by jatin4361 is done by me only but i forget to logged out and signed to aayushibnsl and then created new commit
> added navbar which include home,queries and reviews

- index.html
resolves issue #604  
as the social icons were already present in the footer so i removed the extra sidebar containing social icons
Fixes #(604)
)
before
after changes
@ankit071105  kindly review the PR and merge it into main.
thank you. :)
> removed extra social icons #604

- forgot_password.html
- index.html
- login.html
- register.html
Fixing issues in Navbar and Login page
Fixes #(issue)
- [ ✔️] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> Fixing Issues

- index.html
Issue in the Main Body
Fixes #(issue)
- [ ✔️] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> Fixing UI Of Body

- about.html
- book_condition.html
- buy.html
- contactus.html
- contributor.html
This PR adds a new "Contact Us" page to the website, addressing the absence of a contact page. The page provides users with essential information and a form to reach out to the team.
Fixes #609 
> Fix issue:609 Adding Contact us page

- Ticket-Booking-main1/train_sell.html
> changes added to sell train tickets page

- app.js
Summary of Changes
Related to #638 
This PR implements comprehensive improvements to the ticket management system, focusing on performance optimization, error handling, and architectural improvements. The changes include a new storage management layer, improved form validation, and optimized DOM operations.
Fixes #[Issue Number] - "Refactor Ticket Management System: Performance Optimization and Error Handling Improvements"
Key Changes
✨ Implemented StorageManager class for robust localStorage operations
🔒 Added comprehensive error handling and validation
⚡️ Optimized DOM operations and form handling
🏗️ Restructured code architecture for better maintainability
🧪 Added type safety and validation for critical operations
🎨 Improved form validation with specific user feedback
Motivation and …
>  Implement Robust Error Handling and Performance Optimizations in Ticket Management System

- buy.html
I have removed the duplicate navbar from the buy ticket section.
issue no. : #632
> Removed the duplicate navbar

- index.html
issue #531 
https://github.com/user-attachments/assets/e1b28b13-c522-4e63-9a13-b23e05b2db13
> Working chatbot icon

- faq.css
- faq.js
- index.html
Fixes #615 
https://github.com/user-attachments/assets/9867dc74-b26d-43fe-8ed0-4d604f47e224
@ankit071105 please check this out
> Added animations and smooth scroll to faq section

- buy.html
- styles.css
now buys section is responsive for mobile,mac's and ipad 
my issue no. is #663
> made buys section responsive

- index.html
fixes : #530 
https://github.com/user-attachments/assets/05403ed3-97ef-4458-93fa-87d571e83275
- [ X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> Added improved version of our review section

- index.html
##Change the logo
Fixes #664 
Before:
After:
> twitter logo changed

- sell.html
I'ce aligned the elements of the sell section
Fixes #648 
https://github.com/user-attachments/assets/1e751d63-5014-4a23-8105-5b1371c35890
> Aligned the items in the sell section

- index.html
- travelAware.html
- travelawares.html
Added a new Travel Aware page(responsive) with detailed information about travel resources, tips, and guidelines.
Dark Mode Support: Implemented dark mode styling to improve readability and user experience in low-light settings.
Enhanced UI/UX with improved layout, font adjustments, and color scheme for both light and dark modes.
Fixes #662 
https://github.com/user-attachments/assets/5b918081-4c03-4dd8-a483-d2cc3fe514d7
> ui improvement of travel awareness page

- index.html
- sell.html
Fixed the Disappearance of text in the dark mode issue.
Fixes #656 
https://github.com/user-attachments/assets/23f29f5d-8a98-4d64-a170-878e109a67cd
https://github.com/user-attachments/assets/6e1cdf10-b92e-4520-8517-60dd4fc0c19a
> FIxed the Disappearance of text in the dark mode 

- contributor.css
- contributor.html
- contributor.js
- index.html
- sell.html
I've added a scroll back button for the contributors page.
Fixes #651 
https://github.com/user-attachments/assets/eeef9463-a06c-43eb-9edb-b45f08aa4c12
> Scroll back button for the contributors page 

- contributor.css
- contributor.html
- contributor.js
- index.html
- sell.html
I've Removed the Extra text from the footer
Fixes #650 
> Removed the Extra text from the footer

- index.html
- navbar.css
This pr made the ui of the navbar by creating a toggle button for small pages.
Fixes #534 
https://github.com/user-attachments/assets/ffeacf67-e955-4273-8737-74168ee57eca
> toggle button added

- contributor.css
- contributor.html
- contributor.js
- index.html
- login.html
- sell.html
I've added a footer for the login page.
Fixes #649 
https://github.com/user-attachments/assets/2fdf3a99-d231-4fac-ae36-3950bebc3985
> Login footer

- GroupCookieNotice.html
- index.html
- sitemap.html
Fixes #585 
This pull request introduces two new pages to the website: GroupCookieNotice and SiteMap. These pages provide essential information to users about the site's cookie policy and overall structure.
- **GroupCookieNotice:** This page contains detailed information about the cookies used on the website, including their purpose and how to manage cookie preferences.
- **SiteMap:** This page provides a hierarchical view of the website's structure, making it easy for users to navigate and find specific content.
- Two new links have been added to the footer: "Group Cookie Notice" and "Site Map."
- These links redirect users to the respective pages.
https://github.com/user-attachments/assets/0e142de0-faeb-4c66-9e62-dd534a47b9c0
>  Created GroupCookieNotice and SiteMap Pages

- contactus.html
I've added a navbar to the contact us section
Fixes #653
> Added a navbar to the contact us form.

- about.html
- contactus.html
I've enhanced the user interface section.
Fixes #652 
https://github.com/user-attachments/assets/c20519c4-03a3-47b2-8935-9556ace0bb64
> Enhanced the user interface section

- login.html
I've added a navbar for the login page.
Fixes #683 
> Added a navbar for the login page

- sell.html
now sell section is made responsive for mobile and mac's 
https://github.com/user-attachments/assets/d77410f0-7246-4062-bff8-ab6ae834caed
my issue no. is #670
> make sell section responsive + fixed navbar

- Contribution.md
- buy.html
- contact.html
- fcdoTravel.html
- index.html
- login.html
> Fixes #610: Added FCOD travel advice page

- sell.html
Added a scroll back button to sell section
Fixes #689 
https://github.com/user-attachments/assets/c545f309-3028-49af-9c59-48104164e705
> Added a scroll back button to sell section

- train_sell.html
I update the styking of train_sell.html fully 
Fixes #702 
- [x ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> Fix issue #702 Updating tain_sell.html styling

- train_buy.html
now navbar issue resolved
https://github.com/user-attachments/assets/ae158d88-fb8b-40f8-8688-ce7017744e9e
my issue no. is #699
> resolve the issue of double navbar in buy a train ticket section

- sitemap.html
Summary of Changes This update includes significant improvements to the sitemap.html file. The original version contained multiple issues, including styling conflicts and CSS errors, which affected its visual appeal and functionality. This revision addresses these problems, enhancing readability, layout consistency, and overall aesthetic quality.
Motivation and Context The primary motivation behind this update was to resolve visual inconsistencies and eliminate CSS-related blunders that previously hindered user experience. By refining the structure and fixing styling errors, this change ensures a cleaner, more professional appearance for the sitemap page.
Dependencies No additional dependencies are required for this update.
Fixes #705 
- Bug Fix: Addresses and corrects CSS errors and …
> Fix issue #705 updating fully sitemap.html , resolve isse make look good

- index.html
Fixes:  #(#513)
so basically i just MANIPULATE the  "FEEDBACK" SECTION IN HOME PAGE  which gives the interactive interface for going  smoothly. This page deals with to collecting reviews from users regarding your website.  Transitions ,keyframes are used in these making it more interactive and the the things are unable to show in one picture just go and check  out  the transitions for hovering effects if you like the designing then  please rate it as "level3" or "level 2" label 👍 .
AS I ADDED:-
- give the colors which is in the support of website theme
- resize the feedback size
- add colorful border for interactive user interface
- redesign the whole section
- provide eye catching colors
- ADD HOVER EFFECTS
- ADD TRANSITIONS
- and many more you need to check it out
UI IMPROVEMENT OF …
>  UI IMPROVEMENT OF "FEEDBACK" SECTION IN HOME #513

- index.html
I've added a scroll back button to the main page
Fixes #709 
https://github.com/user-attachments/assets/f4882d66-b1fb-4a68-a1e6-ec5884ec3bc5
> Added a scroll back button to main page

- index.css
- index.html
Removed the white space between navbar and the slider
Fixes #690 
> Removed the white space between navbar and the slider

- buy.html
- contributor.html
- index.css
- index.html
- sell.html
Made the contact us section responsive
Fixes #694 
https://github.com/user-attachments/assets/1f137884-fcb0-4f88-997e-858282bf87d9
> Made the contact us section responsive

- index.html
Changed the next and prev in "See , what our customer say's about us" to '>' and '<' and changed background color to match both dark and light mode.
Fixes #696 
> changed corousel next and prev

- buy.html
- contributor.html
- index.css
- index.html
- sell.html
Rectified the overlapping footer.
Fixes #697 
https://github.com/user-attachments/assets/dcd211db-5900-4c43-969b-cbb487e1bd3f
> Faq section

- index.css
- index.html
Added a simple loader
Fixes #639 
NA
> added a pre-loader to the website

- index.html
I have created contact form for the index.html 
Fixes #704 
Created a good looking form for the front page , keeping an eye on the theme
- [done ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> Contact form created

- about.html
Resolved the black dot in the navbar in the about us section
Resolved the black dot in the navbar in the about us section
Fixes #724 
> Resolved the black dot in the navbar in the about us section

- about.html
scroll back button for the about us section
Fixes #723 
https://github.com/user-attachments/assets/6298d14c-ed35-44d5-b0de-90c089aaeb74
> scroll back button for the about us section

- contactus.html
It imprvove the instability of texts in footer and make it look good like other pages.
Fixes #750 
before:-
after:-
- [✔ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> footer of contact page updated

- index.html
Resolves the problem of collision of FAQ section with the footer
Changes Made:
- Toggle Functionality: Adjusted the JavaScript function to ensure that clicking on a question toggles the visibility of the corresponding answer correctly.
- CSS Updates: Modified the CSS to ensure that the answers are properly displayed without overlapping the footer and maintain a visually appealing layout.
Fixes #716 
> Resolved FAQ section collision with footer

- sell.html
it improvised the sell pages problem and now it is looking better
Fixes #783 
before 
after
> sell page improved

- buy.html
- check_availability.html
What does this PR do?
The **Check Availability page in the Buy Ticket section** lets users verify seat or ticket availability before purchasing. It provides real-time information on available slots, event dates, and seating options, helping users make quick, informed decisions before proceeding with their ticket purchase. This step enhances the booking process by giving clarity on availability upfront.
Fixes #755 
- New feature (non-breaking change which adds functionality)-A check availability page
- [ yes] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> Created a check-availability page for buy ticket section

- index.html
> Transformation

- index.html
Resolved an issue where the mouse cursor trail effect would stop functioning when scrolling down the page. Adjusted the event handling to ensure the cursor trail remains responsive and visible during scroll interactions, maintaining a seamless user experience.
Fixes #744 
https://github.com/user-attachments/assets/976f834b-00ff-4638-b1b3-cf1a562f4b8a
> Fix Cursor Trail Effect During Scroll Events

- index.css
- index.html
- main.css
- test.html
- test2.htm
- test4.htm
Previously the footer and FAQ are overlapped in the home page which was affecting the UI and readability of link in footer section. So i fixed the code.
This PR included the code to separate the FAQ and Footer section which were overlapping previously.
Fixes #740 
> I separated the FAQ and Footer section in the home page.

- index.css
- index.html
Hello, PR
Add new feature - #759
Add a pop up dialog box for Polls/Survey done properly -
https://github.com/user-attachments/assets/0f694dc1-5c67-402e-aa88-90ca890f4859
> Add a pop up dialog box for Polls/Survey done ! #759🌟🌟🌟 

- train_sell.html
Fixes: #727 
https://github.com/user-attachments/assets/bca6b0e1-06be-4024-8b84-245aed453901
> sell train ticket page header resolved

- index.html
- styles.css
This PR was about to Enhance the contact section of home page and succesfully enhanced the page, the changes includes adding hover effect to input boxes , changing backgroung , etc 
Fixes #722 
https://github.com/user-attachments/assets/fcb6d849-8cc5-4d92-beb1-a39b042e7cab
1. Changing the background
2. Changing the text color 
3. Changed the color of placeholder 
4. Added the border radius
5. ETC
> Enhancing the contact-us section of home page

- index.html
@ankit071105 
I have enhanced the faq page
Kindly check it out
https://github.com/user-attachments/assets/ad7c9ac7-8ca1-4c83-b09f-6b4ee2c65996
Fixes #(issue)
> enhanced faq section

- Faq.html
- about.html
- buy.html
- contactus.html
- contributor.html
- index.html
- login.html
- sell.html
i have created a separated responsive FAQ webpage and added its link to footer of all other pages.
Fixes #781 
screenshot
> created a separate FAQ web page 

- terms.html
@ankit071105 
I have changed the wrong detailes in the terms page and enhanced the terms page
Kindly check it out
https://github.com/user-attachments/assets/89542f74-8d29-409d-859b-cb491d4abf96
Fixes #(issue)
> enhanced terms page

- GroupCookieNotice.html
- privacy.html
- sitemap.html
- `Site map` page has only 1  footer now 
-  Added nav bar in `Privacy Policy` page and `Cookie Policy` page 
Fixes #805 
- then
- now
- then
-now
@ankit071105
> `Site map` page has only 1  footer now And; Added nav bar in `Privacy Policy` page and `Cookie Policy` page 

- sitemap.html
Fixed the listing of Sitemap page
Fixes #833 
@ankit071105  I have fixed the issue.
> Sitemap page Listing and Footer Fixed

- sell.html
- train_sell.html
It resolves the whole page of sell bus ticket button.
Fixes #806
https://github.com/user-attachments/assets/e02fe25a-077c-46a6-b895-968f9566ada2
> sell bus ticket page resolved

- index.css
- index.html
This pr will add some effects on map.
Fixes #782 
> Fix issue no. #782 Add some effects on map.

- index.html
> FAQ Page Fixed

- index.html
have changed the href from train_sell.html to sell.html
I have changed the file opening for sell train tickets from train_sell.html to sell.html whose main functionality is to open sell.html itself.
Fixes #810
https://github.com/user-attachments/assets/78436c6d-22ef-4e75-be55-e180b08fbf94
> Changed the file opening for sell train tickets. Fixed #810

- about.html
- book_condition.html
Added the missing Twitter link
> Added twitter link

- fcdoTravel.html
- privacy.html
- travelAware.html
> Added the follow links which were missing in the footer

- privacy.html
> Privacy Footer Page Updated

- ModernSlaveryAct.html
- fcdoTravel.html
- privacy.html
- travelAware.html
> TravelAware Footer 

- ModernSlaveryAct.html
- fcdoTravel.html
- privacy.html
- travelAware.html
> ModernSlaveryAc Footer Page Updated

- index.html
- styles.css
- testp.css
- testp.html
- testp.js
Hello, PR
Add new feature - #875
Add a normal user profile page and a profile icon in the home page navbar that redirects to the profile page done -
Home page -
Profile page -
https://github.com/user-attachments/assets/8bcf646d-a144-4263-871f-d0e645588df2
> Add a User Profiles page done ! #875

- index.html
Fix #943 
- Implemented a poll popup with a close button to dismiss the popup using Font Awesome icons.
- Integrated JavaScript functionality to close the popup.
@ankit071105 Pls assign me this issue give me level, label.
> Added Close button for voteBox

- contactus.html
I was assigned to task to neatly arrrange the footer content of contact us page , successfully completed the task.
Fixes :  #721 
Screenshot :-
Type of change
-neatly arranged the HELPFUL LINKS , ABOUT US , KEEPING SAFE , FIND US ,etc
[ x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> footer change

- index.html
Unwanted content has been removed by updating the index.html . This gives a better UI experience to the users since its now free from all bugs:-)
I have corrected the bugs highlighted in the code and unwanted content has been removed—updated index.html
Fixes #902 
> Unwanted content that appeared on the main page was removed.

- index.html
- sell.html
- sell_bus_ticket.html
- sell_train_ticket.html
This PR fixes the issue of the sell.html by generalizing it to work for both the transports and specific files for each transport separately.
Fixes #878
> Sell train bus ticket files added solving issue #878

- contactus.html
This PR updates the contact us form in order to maintain the uniformity of the website.
Fixes #894
> Update contact us form 

- Faq.html
- buy.html
- contactus.html
- google.html
- help.html
- index.html
- login.html
- privacy.html
- register.html
Fixes #956 
- [.] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> Footer in Register Page

- about.html
Fixes #984
Deleted the unnecessary thing means the things which were causing the isue
**How it now**
**How it was**
> The double button in Abouts page #984

- contactus.html
Missing mouse animation added on contact us page
Fixes #996 
https://github.com/user-attachments/assets/27647221-6d87-4007-86ac-06ce02e4bb7f
> 🛠️FIX : Missing mouse animation added

- index.css
- index.html
- main.css
- styles.css
UPDATED the Slider Button Position and changed the DOTS COLOR making it GOOD LOOKING
BEFORE : 
AFTER : 
Fixes #(issue)
> CHANGED the Slider Button Position and changed the DOTS COLOR making it GOOD LOOKING

- buy.html
- index.css
Make buy page responsive 
Make logo responsive .
Fix the position of  dark-light mode button.
> Make buy page responsive

- index.html
Hello, PR
Remove duplicate header done ! #995
> Remove duplicate header done ! #995

- index.html
Fixed Star rating widget issue in feedback section - #933 
Now it properly working
https://github.com/user-attachments/assets/7d38b173-330d-47a6-84d3-58d5556f218b
> Fixed Star rating widget issue in feedback section ! #933

- contactus.html
Added a scroll-to-top button feature that appears when users scroll down the page, providing an easy way to navigate back to the top of the page with a smooth scrolling animation.
- Implemented a fixed-position button that appears after scrolling down 300px
- Added smooth scrolling behavior using vanilla JavaScript
- Styled the button to match our existing teal theme
- Included hover effects and transitions for better user interaction
- Added proper accessibility attributes for screen readers
https://github.com/user-attachments/assets/9a161046-d6db-4366-8b78-31b39e0ac4f6
1. Scroll down past 300px - verify button appears
2. Click the button - verify smooth scroll to top
3. Scroll up - verify button disappears
4. Test with screen reader - verify accessibility
- Used vanilla JavaScript for …
> feat: Add Scroll-to-Top Button for Better User Navigation

- about.html
Implemented scroll functionality for the existing top button to enable smooth scrolling to top of page.
- Add scroll-to-top functionality
- Implement smooth scrolling behavior
1. Scroll down page
2. Click top button
3. Verify smooth scroll to top
Closes #1013
https://github.com/user-attachments/assets/71e6602b-e875-411a-bcfd-05a6fb4a5d62
> fix: Implement scroll-to-top button functionality in about section!

- index.html
The star colour was not visible, but now it is.
Fixes #1039 
> 🐛[FIX] : Star color is not visible

- register.html
- styles.css
1. Updated the form layout and styling to be more modern and visually appealing
2. Utilized a consistent color scheme, typography, and design elements to match the overall brand
Fixes #1018
> feat(ui): Beautify registration form

- about.html
Missing mouse animation added on the About us page
Fixes #1035
https://github.com/user-attachments/assets/82dd18cc-5b58-4729-a020-7d84f5809613
> 🛠️FIX : Missing mouse animation added 

- sell.html
In sell.html submit button is not making well in css so i fixed that it is showing like a text over the button as submit tickets 
so i fixed that contains
this is the issue  #(issue)
this is video of the issue in sell 
https://github.com/user-attachments/assets/a458901e-4e7d-43fb-874a-d82d6076a777
so i fixed this issue 
https://github.com/user-attachments/assets/af97f6a6-2d1d-4bd4-ab9f-48287b1d81ff
> submit button has been fixed in sell.html 

- footer.css
Fix Footer in FAQ page 
Before -
Now -
> Fix Footer in FAQ page done ! #1073

- terms.html
Add Footer in Terms of use page done ! 
Before -
Now -
> Add Footer in Terms of use page done ! #1076

- check_availability.html
Fix #1092 
**Overview:**  
This PR adds functionality to dynamically display the current year in the footer, ensuring it automatically updates each year without manual intervention.
**Changes:**  
- Added JavaScript code to fetch the current year using `new Date().getFullYear()`.
- Inserted the year into the footer dynamically for accurate and up-to-date copyright information.
**Testing:**  
- Verified that the year displays correctly on page load.
- Tested across multiple browsers to ensure compatibility.
**Why:**  
This change improves accuracy in the footer and reduces maintenance by automating the year update.
@ankit071105 Pls assign me this, give me labels, level.
> Added Dynamic Copyright Year in Check Availability Page

- ModernSlaveryAct.html
Missing mouse animation added on the Modern Slavery Act page .
Fixes #1113 
> 🛠️FIX : Missing mouse animation added on Modern Slavery Act page 

- fcdoTravel.html
Missing mouse animation added on Travel Advice page
Fixes #1117 
> 🛠️FIX : Missing mouse animation added on Travel Advice page

- travelAware.html
Missing mouse animation added on Travel Aware page
Fixes #1115 
> 🛠️FIX : Missing mouse animation added on Travel Aware page

- index.html
> change ui of nav bar menus

- footer.css
- sell.html
fixes the UI of footer part of sell.html
Fixes #1031
> sell.html is improved

- index.html
UPDATED Feedback Form
BEFORE : 
AFTER : 
Fixes #(issue)
> UPDATED Feedback Form

- about.html
CHANGED the ABOUT US Section
BEFORE : 
AFTER : 
> CHANGED the ABOUT US Section View
